[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/tty.SLAB_USBtoUART
monitor_port = /dev/tty.SLAB_USBtoUART
lib_deps = 
    h2zero/NimBLE-Arduino @ ^1.4.0 